# Generated by Django 4.2.24 on 2025-11-22 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='city',
            field=models.CharField(default='Mumbai', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='pincode',
            field=models.CharField(default='400076', max_length=10),
            preserve_default=False,
        ),
    ]
